# Generated by Django 4.1.1 on 2023-07-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('pimage', models.ImageField(upload_to='C:\\venv\\Ecommerce\\static\\media')),
                ('pdetail', models.TextField(max_length=100)),
                ('pprice', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eemail', models.EmailField(max_length=30)),
                ('epass', models.IntegerField()),
                ('eimage', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
