# Generated by Django 4.1.1 on 2023-07-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='ptitle',
            field=models.TextField(default='non', max_length=20),
        ),
    ]
