# Generated by Django 4.1.1 on 2023-07-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_cartdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdetail',
            name='userid',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='cartdetail',
            name='pnumber',
            field=models.IntegerField(default=1),
        ),
    ]
