# Generated by Django 4.1.1 on 2023-07-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_cartdetail_userid_alter_cartdetail_pnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='ename',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
