# Generated by Django 4.1.1 on 2023-07-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_visitor_ename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('ptitle', models.CharField(max_length=10)),
                ('pprice', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pnumber', models.IntegerField()),
                ('ename', models.CharField(max_length=20)),
                ('eemail', models.EmailField(max_length=30)),
            ],
        ),
    ]
