# Generated by Django 4.1.1 on 2023-07-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='userid',
            field=models.IntegerField(default=None),
        ),
    ]
