# Generated by Django 4.1.1 on 2023-08-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
